<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\map.png" />
    <Resource Include="Resources\solar_panel.png" />
    <Resource Include="Resources\icon.ico" />
  </ItemGroup>

</Project>
